name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "data/**"
      - "params.yaml"
      - "MLproject"
      - "requirements.txt"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Pull Data with DVC
        run: dvc pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t julianzeilinger/mlflow-test:latest .
          docker push julianzeilinger/mlflow-test:latest

      - name: Configure Kubernetes Access
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBECONFIG}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          kubectl get pods -n mlflow

      - name: Port Forward MLflow Tracking Server
        run: |
          kubectl port-forward svc/mlflow-tracking -n mlflow 5000:5000 &
          sleep 5 # Ensure port forwarding is active

      - name: Run MLflow Project on Kubernetes
        env:
          MLFLOW_TRACKING_URI: http://localhost:5000
        run: |
          mlflow run . --backend kubernetes --backend-config backend-config.json
