name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - "framework-tests/mlflow/src/**"
      - "framework-tests/mlflow/data/**"
      - "framework-tests/mlflow/params.yaml"
      - "framework-tests/mlflow/MLproject"
      - "framework-tests/mlflow/requirements.txt"
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install -r framework-tests/mlflow/requirements.txt

      - name: Install DVC
        run: pip install dvc[s3]

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: VzKqqPTjYFGfOS3TaFuz
          aws-secret-access-key: Hs9uJYgF5LwPP3RuLI21PohYGKKIll4JducVlRuD
          aws-region: us-east-1

      - name: Pull Data with DVC
        run: dvc pull

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          docker build -t julianzeilinger/mlflow-test:${{ github.sha }} .
          docker push julianzeilinger/mlflow-test:${{ github.sha }}

      - name: Update MLproject File
        run: |
          sed -i 's|julianzeilinger/mlflow-test:.*|julianzeilinger/mlflow-test:${{ github.sha }}|' MLproject
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update Docker image to ${{ github.sha }}"
          git push origin main

      - name: Run MLflow Project on Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        run: |
          echo "${KUBECONFIG}" | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          mlflow run . --backend kubernetes --backend-config framework-tests/mlflow/backend-config.yaml
